In [1]:
from rapidsegment import *

In [3]:
data = UniversalDataLoader(file_path = "/workspaces/RapidSegment/stress_test/stress_data.parquet").load()

2026-08-11 13:23:25,472 | INFO     | [data_loader.py:147] | 📂 Loading file: /workspaces/RapidSegment/stress_test/stress_data.parquet (extension: .parquet)

In [16]:
builder = StrategicSegmentBuilder(target="target", binning_method="optimal", db_path=":memory:", db_temp_dir="/tmp", selection_metric="iv",
                                  min_lift = 1, min_events = 1, min_sample_size = 10)

In [17]:
segment = builder.extract_segments(data)

2026-08-11 13:28:20,662 | INFO     | [builder.py:981] | 🚀 Starting hierarchical segment extraction...
2026-08-11 13:28:20,678 | INFO     | [builder.py:1004] | ⚙️ DuckDB Configured for Disk Spilling: Threads=4/4, MemoryLimit=12GB, TempDir=/tmp
2026-08-11 13:28:20,678 | INFO     | [builder.py:1008] | 📊 Sort priority: lift_rate_count
2026-08-11 13:28:20,679 | INFO     | [builder.py:1009] | 📦 Binning method: optimal (naive_bins=5)
2026-08-11 13:28:20,729 | INFO     | [builder.py:1060] | 🔒 Locking Original Base Rate: 10.21%
2026-08-11 13:28:20,731 | INFO     | [builder.py:1083] | 🔄 Iteration 1 | Remaining Volume: 50,000 | Base Rate: 10.21%
2026-08-11 13:28:20,732 | INFO     | [builder.py:266] | 🔍 Computing IV and bins for 10 features...
2026-08-11 13:28:22,174 | WARNING  | [builder.py:1254] | ⚠️ Iteration 1: No candidate passed hard constraints. Stopping.
2026-08-11 13:28:22,183 | INFO     | [builder.py:1419] | 🏁 Extraction complete.

In [12]:
eval = builder.evaluate_final_coverage(data)
pd.DataFrame(eval)

2026-08-11 13:26:35,907 | INFO     | [builder.py:1429] | 📊 Evaluating final hierarchical coverage on original data...

,segment,total_count,target_events,response_rate,base_response_rate,capture_rate,lift,cumulative_sample_capture,cumulative_event_capture
0,1,1814,1016.0,56.008820,10.206,3.628,5.487833,3.628,19.909857
1,2,1809,423.0,23.383085,10.206,3.618,2.291112,7.246,28.199099
2,0,46377,3664.0,7.900468,10.206,92.754,0.774100,100.000,100.000000

In [10]:
import pandas as pd
pd.DataFrame(segment)

,segment_id,rule_string,sql_filter,count,rate,lift,meta_applied_sample_size,meta_applied_min_lift
0,1,flag_str=[1] & region=[Normal_Segment_A] & ten...,(flag_str = '1') AND (region IN ('Normal_Segme...,1814,56.008820,5.487833,1000,2.0
1,2,"income=[76884.356, inf) & balance=[-inf, 575.44)",(income >= 76884.356) AND (balance < 575.44),1809,23.383085,2.291112,1000,2.0

In [18]:
data.schema

income: double
tenure_days: double
balance: double
noise_num: double
constant_num: double
region: large_string
high_card_id: large_string
constant_cat: large_string
noise_cat: large_string
flag_str: large_string
target: double